apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-svc-deployment
  labels:
    app: person-svc
spec:
  selector:
    matchLabels:
      app: person-svc
  template:
    metadata:
      labels:
        app: person-svc
    spec:
      containers:
        - name: person-svc
          image: __IMAGE__
          ports:
            - containerPort: 80
